version: '3.7'
# env_file: "./Docker/config/env"
services:
  
  elasticsearch:
    env_file: "./Docker/config/env"
    image: elasticsearch:7.9.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    ports: 
      - "9200:9200"
      - "9300:9300"
    volumes: 
      - ./Docker/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      for-surikata:
        ipv4_address: 192.168.205.18
   
  kibana:
    image: kibana:7.9.1
    env_file: "./Docker/config/env"
    container_name: kibana
    ports:
      - "5601:5601"
    volumes: 
      - ./Docker/config/kibana.yml:/usr/share/kibana/config/kibana.yml     
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      for-surikata:
        ipv4_address: 192.168.205.19
    depends_on: 
      - elasticsearch

  logstash:
    image: logstash:7.9.1
    env_file: "./Docker/config/env"
    container_name: logstash
    depends_on:
    - elasticsearch   
    ports:
    - "9600:9600"
    volumes: 
      - ./Docker/config/to_elastic.conf:/usr/share/logstash/pipeline/logstash.conf
      # - ./Docker/config/logstash.yml:/usr/share/logstash/config/logstash.yml
    networks: 
      for-surikata:
        ipv4_address: 192.168.205.20
    depends_on: 
      - elasticsearch
  
  suricata:
    container_name: suricata
    build:
      context: "Docker"
      dockerfile: Dockerfile
      # image: suricata_test
      # ERROR: The Compose file './docker-compose.yml' is invalid because:
      # services.suricata.build contains unsupported option: 'image'
    volumes:
      - ./Docker/config/suricata.yaml:/etc/suricata/surikata.yaml
    
    network_mode: "host"

networks: 
  for-surikata:
    ipam:
      driver: default
      config:
        - subnet: 192.168.205.16/28